name: Update

on:
  schedule:
    - cron:  '15 8 */7 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests BeautifulSoup4
    - name: Fetching data
      run: |
        python cn.py
    - name: Git Commit
      env:
        GitEmail: ${{ secrets.GitEmail }}
        GitName: ${{ secrets.GitName }}
      run: |
        git add -A .
        git config --local user.email "$GitEmail"
        git config --local user.name "$GitName"
        git commit -am "Updated: `date +'%Y-%m-%d %H:%M:%S'` UTC"
    - name: Git Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
